# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppnewuser_details.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from aainfo import Ui_Dialog8
import mysql as mdb
import mysql.connector
from mysql.connector import Error
from mysql.connector import errorcode

def connect():
    """ Connect to MySQL database """
    try:
        conn = mysql.connector.connect(host='localhost',
                                       database='railway_concession',
                                       user='root',
                                       password='')
        if conn.is_connected():
            print('Connected to MySQL database')
 
    except Error as e:
        print(e)
 
    finally:
        conn.close()
 
 
if __name__ == '__main__':
    connect()

class Ui_Dialog6(object):
    def InsertData(self):
        con= mdb.connector.connect(host="localhost",user="root", passwd="",db="railway_concession")

        #with con:
        cur = con.cursor()  
        cur.execute('''INSERT INTO `stud_details`(`name`, `date_of_birth`, `contact`, `stud_id`, `gender`, `email`, `city`, `address`, `branch`, `year`, `semester`, `start_station`, `end_station`, `rail_line`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)''', 
                           ( self.lineEdit_8.text(),
                             self.lineEdit_2.text(),
                             self.lineEdit_7.text(),
                             self.lineEdit_6.text(),
                             self.comboBox_10.currentText(),
                             self.lineEdit_4.text(),
                             self.lineEdit_5.text(),
                             self.lineEdit_3.text(),
                             self.comboBox_4.currentText(),
                             self.comboBox_6.currentText(),
                             self.comboBox_5.currentText(),
                             self.lineEdit.text(),
                             self.comboBox_8.currentText(),
                             self.comboBox_9.currentText(),
                             
                                                          )
                       )            
        cur.close()
        #QMessageBox.information(self, "Connection", "Data Inserted Successfully")
        self.lineEdit_8.setText('')
        self.lineEdit_2.setText('')
        self.lineEdit_7.setText('')
        self.lineEdit_6.setText('')
        self.comboBox_10.currentText('')
        self.lineEdit_4.setText('')
        self.lineEdit_5.setText('')
        self.lineEdit_3.setText('')
        self.comboBox_4.currentText('')
        self.comboBox_6.currentText('')
        self.comboBox_5.currentText('')
        self.lineEdit.setText('')
        self.comboBox_8.currentText('')
        self.comboBox_9.currentText('')
        
        
        self.initWindow() 
    def newText(self):
        if self.lineEdit_8.text() and self.lineEdit_2.text() and self.lineEdit_7.text() and self.lineEdit_6.text() and self.comboBox_10.currentText() and self.lineEdit_4.text() and self.lineEdit_5.text() and self.lineEdit_3.text() and self.comboBox_4.currentText() and self.comboBox_6.currentText() and self.comboBox_5.currentText() and self.lineEdit.text() and self.comboBox_8.currentText() and self.comboBox_9.currentText() :
            self.button.setEnabled(True)
        else:
            self.button.setEnabled(False)
            
    def info(self):
        self.aainfoWindow=QtWidgets.QDialog()
        self.ui=Ui_Dialog8()
        self.ui.setupUi(self.aainfoWindow)
        self.aainfoWindow.show()
            
            
    def setupUi(self, Dialog6):
        Dialog6.setObjectName("Dialog6")
        Dialog6.resize(1106, 866)
        Dialog6.setStyleSheet("QDialog {\n"
"background-color:rgb(255, 255, 255);\n"
"    \n"
"}\n"
"")
        self.label = QtWidgets.QLabel(Dialog6)
        self.label.setGeometry(QtCore.QRect(10, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog6)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 360, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog6)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 410, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        
        
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog6)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 460, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        
        self.pushButton = QtWidgets.QPushButton(Dialog6)
        self.pushButton.setGeometry(QtCore.QRect(500, 820, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        #
        self.pushButton.clicked.connect(self.InsertData)
        self.pushButton.clicked.connect(self.info)
        
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog6)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 280, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog6)
        self.lineEdit_7.setGeometry(QtCore.QRect(230, 230, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog6)
        self.lineEdit_8.setGeometry(QtCore.QRect(230, 140, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.layoutWidget = QtWidgets.QWidget(Dialog6)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 140, 171, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(640, 570, 192, 161))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog6)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 580, 151, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(200, 570, 191, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget_4.setFont(font)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_4)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_6)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_5)
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(820, 570, 191, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget_5.setFont(font)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_8)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_9)
        self.label_21 = QtWidgets.QLabel(Dialog6)
        self.label_21.setGeometry(QtCore.QRect(10, 530, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog6)
        self.label_22.setGeometry(QtCore.QRect(600, 530, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog6)
        self.label_23.setGeometry(QtCore.QRect(0, 0, 1111, 71))
        self.label_23.setStyleSheet("\n"
"background-color: rgb(0, 170, 255);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_8 = QtWidgets.QLabel(Dialog6)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog6)
        self.comboBox_10.setGeometry(QtCore.QRect(230, 320, 301, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog6)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 190, 301, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog6)
        QtCore.QMetaObject.connectSlotsByName(Dialog6)

    def retranslateUi(self, Dialog6):
        _translate = QtCore.QCoreApplication.translate
        Dialog6.setWindowTitle(_translate("Dialog6", "Dialog"))
        self.label.setText(_translate("Dialog6", "Personal Details :"))
        self.pushButton.setText(_translate("Dialog6", "Submit"))
        self.label_2.setText(_translate("Dialog6", "Name :"))
        self.label_3.setText(_translate("Dialog6", "Date of Birth :"))
        self.label_4.setText(_translate("Dialog6", "Contact :"))
        self.label_5.setText(_translate("Dialog6", "Student ID :"))
        self.label_6.setText(_translate("Dialog6", "Gender :"))
        self.label_7.setText(_translate("Dialog6", "Email :"))
        self.label_9.setText(_translate("Dialog6", "City :"))
        self.label_10.setText(_translate("Dialog6", "Address :"))
        self.label_15.setText(_translate("Dialog6", "Starting station :"))
        self.label_16.setText(_translate("Dialog6", "Ending Station :"))
        self.label_17.setText(_translate("Dialog6", "Railway Line :"))
        self.label_18.setText(_translate("Dialog6", "Department :"))
        self.label_19.setText(_translate("Dialog6", "Year :"))
        self.label_20.setText(_translate("Dialog6", "Semester :"))
        self.comboBox_4.setItemText(0, _translate("Dialog6", "IT"))
        self.comboBox_4.setItemText(1, _translate("Dialog6", "COMPS"))
        self.comboBox_4.setItemText(2, _translate("Dialog6", "EXTC"))
        self.comboBox_4.setItemText(3, _translate("Dialog6", "MECH"))
        self.comboBox_6.setItemText(0, _translate("Dialog6", "FE"))
        self.comboBox_6.setItemText(1, _translate("Dialog6", "SE"))
        self.comboBox_6.setItemText(2, _translate("Dialog6", "TE"))
        self.comboBox_6.setItemText(3, _translate("Dialog6", "BE"))
        self.comboBox_5.setItemText(0, _translate("Dialog6", "I"))
        self.comboBox_5.setItemText(1, _translate("Dialog6", "II"))
        self.comboBox_5.setItemText(2, _translate("Dialog6", "III"))
        self.comboBox_5.setItemText(3, _translate("Dialog6", "IV"))
        self.comboBox_5.setItemText(4, _translate("Dialog6", "V"))
        self.comboBox_5.setItemText(5, _translate("Dialog6", "VI"))
        self.comboBox_5.setItemText(6, _translate("Dialog6", "VII"))
        self.comboBox_5.setItemText(7, _translate("Dialog6", "VIII"))
        self.comboBox_8.setItemText(0, _translate("Dialog6", "Vidyavihar"))
        self.comboBox_8.setItemText(1, _translate("Dialog6", "SantaCruz"))
        self.comboBox_9.setItemText(0, _translate("Dialog6", "Central Line"))
        self.comboBox_9.setItemText(1, _translate("Dialog6", "Western Line"))
        self.label_21.setText(_translate("Dialog6", "Academic Details :"))
        self.label_22.setText(_translate("Dialog6", "Additional Details :"))
        self.label_8.setText(_translate("Dialog6", "Student Details"))
        self.comboBox_10.setItemText(0, _translate("Dialog6", "Male"))
        self.comboBox_10.setItemText(1, _translate("Dialog6", "Female"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog6", "YYYY-MM-DD"))
        self.lineEdit_2.textChanged.connect(self.newText)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog6 = QtWidgets.QDialog()
    ui = Ui_Dialog6()
    ui.setupUi(Dialog6)
    Dialog6.show()
    sys.exit(app.exec_())

